# see https://github.com/travis-ci/travis-ci/issues/3040

language: objective-c
osx_image: xcode7.3
branches:
  only:
  - master

before_install:
  - DEVICE='iPhone 6'
  - IOS_VERSION='9.3'
  - SIMULATOR_ID=$(xcrun instruments -s | grep -o "$DEVICE ($IOS_VERSION) \[.*\]" | grep -o "\[.*\]" | sed "s/^\[\(.*\)\]$/\1/")
  - brew update
  - brew upgrade
  - brew install swiftlint
  - bundle install
  - pod repo update

script:
  - bundle exec danger
  - echo $SIMULATOR_ID
  - open -b com.apple.iphonesimulator --args -CurrentDeviceUDID $SIMULATOR_ID
  - set -o pipefail
  - xcodebuild clean build test -workspace CocoaHeadsApp.xcworkspace -scheme CocoaHeadsApp -sdk iphonesimulator -destination "platform=iOS Simulator,name=$DEVICE,OS=$IOS_VERSION" | xcpretty -c

notifications:
  email: false
  slack: iosdevbr:jdozLqf7LLjEeho9PB3uRL6S
