language: objective-c
branches:
  only:
  - master
git:
  submodules: false
before_install: 
  - git submodule update --init --recursive
  - bundle install
  - cd CocoaHeadsApp
  - bundle exec pod keys set ParseClientKey [ "${TRAVIS_PULL_REQUEST}" = "false" ] && $ParseClientKey || '-'
  - bundle exec pod keys set ParseApplicationId [ "${TRAVIS_PULL_REQUEST}" = "false" ] && $ParseApplicationId || '-'
  - cd ..
podfile: CocoaHeadsApp/Podfile
xcode_workspace: CocoaHeadsApp/CocoaHeadsApp.xcworkspace
xcode_scheme: CocoaHeadsApp
script: xctool -workspace CocoaHeadsApp/CocoaHeadsApp.xcworkspace -sdk iphonesimulator -scheme CocoaHeadsApp build test CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
osx_image: xcode7.2
notifications:
  email: false
env:
  global:
  - secure: "U/EPsCObDKJF/rJVyixEuEkmFgQc+8LHdB0j+FUBNSkrjbNsQkNwpBYGe4F5xqIGsRoPpibevkl9ixq+DodNMND/NlqHV/JuftLJ9diAwbsm0AkngfhUPHVBW+x0gYvNvmD5Rky02Whmt4ktptWQpoYsOMPy+iy8Ros9+V8TAa3pnHJl2CVdKcwl9jQRE6YGtfdKGYCKxNh9ZxqG3EuCFq8mq59v0aoLHkt3zUtbHYtDovTzC6CuAnr7V0EZtD3MNmL9jOnjKWMWsH2tH7b6lLZklcxUQhSUeJ59vodcKgT6VcWkTP9zOayaUrCBN6AQ1BPeNUcaDg97izIcYp8+UHHOl7XVsgj+J0GArXlBy9Yq3zrD9nzzg6vYjFL88ixDwxcVbEBnLR/C6wvBqdoVn/Za8FX7XpklccxS8pcme1i7xNMk2+R6LoQLh7QOJAcP/gG7yufAjyXdgG0FWbGAtk8LV4WmKqD9dmMl+T1ZUAlPQT0IbD5kPQJlZ0xoj4OXuCnYOGrTkPKD8wafZwNfbksyuX+mjV5LiTRGwfQCQM6sUyCDgJF9Bwgax7Ee5Lp25Hoa0Bn8w6zNbiDlDuGoYEKwr/l37Bq5xkNJ+Wv1s6KbHeF/dYbjWSht000O2PC3l81IrnHsYwg/obwGqi+WlK+6bUqvNYIhe7Wv7xUSgvQ="
  - secure: "TLSFBmovvWVI7GMlajiDMWptOIIuvtKgzh+SHM+rCfT2+DJUGVUXDuG1V2KNxCczvNFG2ciCLu5HGrPoTTIJtz/UnDcqIKis8BBH827inyIGYDu2E92nWs34idoRTQ9rYdaBTzuJNWCRFGO4jENg4C49Sl8AJGiZkUVI4ZhkFa/B1h4atSYecrtuCLr3bkGDxK3ajxSKHMj+GNClRi80AhNr2pQiUNHbklVSg8bYp6B555XaRTcVSC3AYLOOyTIblU7ZRgnv3+AGQk5JwqHQczaIzwvI+aicY7vXwFsgsgaXnT3cmDXMwI887RcFNzsyZUxXsgx7mpgi6C+aID+4LttxYNmSSYg2EABuVEq5fqe5RIsq6iO7F33pS9s/9Ij5lcND4QE6UTKfnWOC10UoUP1I6e4Nvd/81unJ/KYZFhteniszIBj8iGRh93wIE3bl1QbGPksmU7TAsze184Rk1PhIny0pmQTJQTLMc9sLS8yOTgf5do8HaZzfThZ6CJ9sLMClCldgDMrGeEq4TVLJJGs0tTI3zY4tc3hFZ8d/sDGHk4+ZahkdWjhCMW3CMmS6r6nCNbX0wRmULNFxWhFTkNjJmq/zt2JaSEZcUQXH2q9kMAgcjwZweY2HdwbDyVD7Xh2psk7tizAI3gYeuoxXFjEF3K719OfPJek78R3tWaM="
